# Generated by Django 4.2.10 on 2024-02-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='start',
            new_name='stars',
        ),
    ]
